
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mylogin?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  resources:
    static-locations: classpath:/templates/


  thymeleaf:
    # ???? false?????? true
    cache: false

mybatis-plus:
  global-config:
    db-config:
      id-type: auto # ????
  mapper-locations: com/example/springbootfour/mapper/xml/*.xml
  type-aliases-package: com.example.springbootfou.pojo

logging:
  level:
    com.huang.login2.mapper: trace